version: '3.7'
services:
  bot:
    build: .
    environment:
      - BOT_TOKEN=<bot_token>
      - DB_HOST=<db_host>
      - DB_USER=<db_user>
      - DB_PASSWD=<db_passwd>
      - DB_NAME=<db_name>
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: db
    hostname: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=<db_passwd>
      - MYSQL_DATABASE=<db_name>
      - MYSQL_USER=<db_user>
      - MYSQL_PASSWORD=<db_passwd>
    volumes:
    - ./data:/var/lib/mysql
    ports:
    - 3306:3306
